"""fixed not nullable fields

Revision ID: 28409ff38cf0
Revises: 436c59fdac80
Create Date: 2023-04-21 21:20:49.482649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28409ff38cf0'
down_revision = '436c59fdac80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cooked_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('closed_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('wday_opening',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('wday_closing',
               existing_type=postgresql.TIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('wday_closing',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('wday_opening',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('closed_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('cooked_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
