"""Added images paths to dish and restaurant

Revision ID: cbf7ef0319ef
Revises: 28409ff38cf0
Create Date: 2023-05-09 13:49:15.206399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf7ef0319ef'
down_revision = '28409ff38cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
